### ISSUE TITLE
gradio error 관련 질문 드립니다.

### ISSUE THREAD

**Issue by hyunjioh02** [hsnam95/class2022Spring#25]
안녕하세요 교수님! 2021130824 오현지입니다.
함수를 만드는 과정까지는 오류가 없다고 나오는데 함수를 gradio로 내보내면 gradio에서 어떤 값을 submit해도 에러가 뜹니다. 어디에서 오류가 난 것인지 궁금합니다.
https://colab.research.google.com/github/hyunjioh02/2022-spring/blob/main/20220328.ipynb

![캡처](https://user-images.githubusercontent.com/101513682/161884220-3405cfa0-516b-4211-8d05-027238ea788d.PNG)

**Comment by hsnam95** [comment]
아마 '20220405'는 될 겁니다. 매뉴얼을 보면 하루 전까지만 되는 것 같아요.

**Comment by hyunjioh02** [comment]
감사합니다!
