### ISSUE TITLE
test 함수와 gradio

### ISSUE THREAD

**Issue by Ko4rii** [hsnam95/class2022Spring#8]
안녕하세요! 영어음성학응용 수강중인 영어영문학과 2021130828 고서현입니다!
교수님이 가르쳐주신 대로 test 함수를 정의하려 했는데 제가 사용한 API URL에는 교수님이 사용하신 'sidoName'처럼 입력할 수 있는 값이 없다는 것을 발견했습니다. 요청 메시지 중 값을 변경할 수 있는 것은 pageNo와 numOfRows 뿐인데 이런 경우에는 어떻게 함수를 정의해야 하나요?

아래는 제가 사용한 URL입니다!
'http://apis.data.go.kr/6260000/FoodService/getFoodEn?serviceKey=IfP6S3pUTEI5Xq%2FKPo5zzDnltUmDq9%2B6KYfhC7NOiB89K388mQOtSNOd5Nmg%2F%2Fmrv43Nvk84kTPqX2ndOG2%2B2g%3D%3D&numOfRows=100&pageNo=1&resultType=json'

**Comment by hsnam95** [comment]
그런 식으로 요청할 수 있는 게 없는 API 서비스입니다. 여러 변수로 요청 가능한 서비스를 찾아서 이용해 보세요.

**Comment by Ko4rii** [comment]
알겠습니다. 감사합니다!
